model:
  forward_mode: joint  # options: joint, discriminative_only
  discriminative:
    model_name: nvidia/segformer-b5-finetuned-ade-640-640
    num_classes: 150
    short_edge: 512
    device: cuda:0
  generative:
    model_path: stabilityai/stable-diffusion-3-medium-diffusers
    prompt: a photo of a {}
    window_size: 512
    stride: 256
    topk: 1
    classes_threshold: 20
    device_primary: cuda:0
    device_secondary: cuda:1
